apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/*
build:
  local:
    push: false
  artifacts:
    - image: veilhelmalexander/golfin-client
      context: ../golfin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: veilhelmalexander/golfin-register-user
      context: registerUser
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: veilhelmalexander/golfin-login-user
      context: loginUser
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: veilhelmalexander/golfin-transaction
      context: Transaction
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: veilhelmalexander/golfin-totals
      context: totalsService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: veilhelmalexander/golfin-goals
      context: goalsService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: veilhelmalexander/golfin-query
      context: queryService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: veilhelmalexander/event-bus
      context: eventBusService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
