apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: veilhelmalex/golfin-client
          env:
            - name: REACT_APP_REGISTER_USER_SERVICE_URL
              value: http://golfin.veilhelmalexander.com:3000/users
            - name: REACT_APP_QUERY_SERVICE_URL
              value: http://golfin.veilhelmalexander.com:3003/query
            - name: REACT_APP_TRANSACTION_SERVICE_URL
              value: http://golfin.veilhelmalexander.com:3002/transaction
            - name: REACT_APP_LOGIN_SERVICE_URL
              value: http://golfin.veilhelmalexander.com:3001/login
            - name: REACT_APP_GOALS_SERVICE_URL
              value: http://golfin.veilhelmalexander.com:3005/goals
            - name: PORT
              value: 4000
            
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 4000
      targetPort: 4000
