apiVersion: apps/v1
kind: Deployment
metadata:
  name: goals-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goals
  template:
    metadata:
      labels:
        app: goals
    spec:
      containers:
        - name: goals
          image: veilhelmalex/golfin-goals
          env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: goals-config
                  key: DB_URI
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: goals-config
                  key: SECRET_KEY
            - name: EVENT_BUS_URL
              value: http://golfin.veilhelmalexander.com:5000
            - name: REGISTER_USER_URL
              value: http://golfin.veilhelmalexander.com:3005/goals/recieveEvents
            - name: PORT
              value: "3005"
---
apiVersion: v1
kind: Service
metadata:
  name: goals-srv
spec:
  selector:
    app: goals
  ports:
    - name: goals
      protocol: TCP
      port: 3005
      targetPort: 3005
