apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-user
  template:
    metadata:
      labels:
        app: login-user
    spec:
      containers:
        - name: login-user
          image: veilhelmalex/golfin-login-user
          env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: login-config
                  key: DB_URI
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: login-config
                  key: SECRET_KEY
            - name: EVENT_BUS_URL
              value: http://golfin.veilhelmalexander.com:5000
            - name: LOGIN_USER_URL
              value: http://golfin.veilhelmalexander.com:3001/login/recieveEvents
            - name: PORT
              value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: login-user-srv
spec:
  selector:
    app: login-user
  ports:
    - name: login-user
      protocol: TCP
      port: 3001
      targetPort: 3001
