apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: veilhelmalex/golfin-query
          env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: DB_URI
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: SECRET_KEY
            - name: EVENT_BUS_URL
              value: http://golfin.veilhelmalexander.com:5000
            - name: REGISTER_USER_URL
              value: http://golfin.veilhelmalexander.com:3003/query/recieveEvents
            - name: PORT
              value: "3003"
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 3003
      targetPort: 3003
