apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-user
  template:
    metadata:
      labels:
        app: register-user
    spec:
      containers:
        - name: register-user
          image: veilhelmalex/golfin-register-user
          env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: register-user-config
                  key: DB_URI
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: register-user-config
                  key: SECRET_KEY
            - name: EVENT_BUS_URL
              value: http://golfin.veilhelmalexander.com:5000
            - name: REGISTER_USER_URL
              value: http://golfin.veilhelmalexander.com:3000/users/recieveEvents
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: register-user-srv
spec:
  selector:
    app: register-user
  ports:
    - name: register-user
      protocol: TCP
      port: 3000
      targetPort: 3000
