apiVersion: apps/v1
kind: Deployment
metadata:
  name: totals-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: totals
  template:
    metadata:
      labels:
        app: totals
    spec:
      containers:
        - name: totals
          image: veilhelmalex/golfin-totals
          env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: totals-config
                  key: DB_URI
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: totals-config
                  key: SECRET_KEY
            - name: EVENT_BUS_URL
              value: http://golfin.veilhelmalexander.com:5000
            - name: REGISTER_USER_URL
              value: http://golfin.veilhelmalexander.com:3004/totals/recieveEvents
            - name: PORT
              value: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: totals-srv
spec:
  selector:
    app: totals
  ports:
    - name: totals
      protocol: TCP
      port: 3004
      targetPort: 3004
